name: ServerTools
main: alexplugins.servertools.ServerTools
version: 0.0.1
api-version: 1.21
author: AlexPlugins Team
description: Simple Server Tools to help your server!

commands:
  servertools:
    description: ServerTools Testing Command
    usage: /servertools
    permission: alexplugins.servertools.commands.servertools
    permission-message: "You need permission to run this command!"
  disconnect:
    description: Disconnect from the server!
    usage: /disconnect
  stopserver:
    description: Stop the server and kick all players
    usage: /stopserver
    permission: alexplugins.servertools.commands.stopserver
    permission-message: "You need permission to run this command!"
    